title: Sergey Barseghyan # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
baseurl: ""
description: > # your text below (remove <br> elements if you don't need line breaks)
email: sergey.barseghyan06@gmail.com
github_username: scaevola96
  <br>Theoretical physicist<br>

  <br><br>
  <a href="https://www.linkedin.com/in/sergey-barseghyan-398a69125/">View My LinkedIn Profile</a> 
  
# theme: jekyll-theme-minimal
remote_theme: fongandrew/hydeout
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-remote-theme

