title: Sergey Barseghyan
author: GitHub User
email: sergey.barseghyan06@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Theoretical Physicist
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Sergey Barseghyan
  tagline: Theoretical Physicist. Quant
  date_format: "%b %-d, %Y"
  style: minimal
  showNav: true
  showPicker: true

  # generate social links in footer
  social_links:
    github:  scaevola96
    linkedIn: https://www.linkedin.com/in/sergey-barseghyan-398a69125/
  
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed